local MixDatabase = {
    {	MixName = "O.B.G Season Evolution",
        SortingMethods = {
            {   SortName = "Full Display Mode",
                AvailableSongs = {
                    { SongTitle = "ANOTHER TRUTH | CORDIALITY", Charts = { "3RD-NORMAL", "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "EXTRAVAGANZA", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
                    { SongTitle = "FINAL AUDITION 2", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
                    { SongTitle = "NAISSANCE", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
                    { SongTitle = "TURKEY MARCH", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
                    { SongTitle = "WITH MY LOVER", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "AN INTERESTING VIEW", Charts = { "3RD-HARD", "3RD-CRAZY" } },
                    { SongTitle = "NIGHTMARE", Charts = { "3RD-NORMAL", "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "CLOSE YOUR EYES", Charts = { "3RD-NORMAL", "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "FREE STYLE", Charts = { "3RD-NORMAL", "3RD-DOUBLE" } },
                    { SongTitle = "MIDNIGHT BLUE", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "SHE LIKES PIZZA", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
                    { SongTitle = "PUMPING UP", Charts = { "3RD-HARD" } },
                    { SongTitle = "DON'T BOTHER ME | CAUTION", Charts = { "3RD-NORMAL", "3RD-DOUBLE" } },
                    { SongTitle = "LOVE SONG", Charts = { "3RD-NORMAL", "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "LOVER'S GRIEF | SORROW", Charts = { "3RD-NORMAL", "3RD-DOUBLE" } },
                    { SongTitle = "TO THE TOP", Charts = { "3RD-NORMAL", "3RD-HARD" } },
                    { SongTitle = "SEPARATION WITH HER", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "PUYO PUYO", Charts = { "3RD-NORMAL", "3RD-DOUBLE" } },
                    { SongTitle = "WE ARE", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "TIME TO SAY GOODBYE", Charts = { "3RD-NORMAL", "3RD-HARD", "3RD-CRAZY" } },
                    { SongTitle = "TELL ME (BY JINUSEAN)", Charts = { "3RD-HARD" } },
                    { SongTitle = "OK? OK! (BEAUTY AND THE BEAST)", Charts = { "3RD-NORMAL", "3RD-DOUBLE" } },
                    { SongTitle = "OH! ROSA", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "FIRST LOVE (BY BANYA)", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "BETRAYER", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "SOLITARY", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "MR. LARPUS", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "SAD SALSA", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "SUMMER OF LOVE", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "KISS", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "MAN & WOMAN", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "FIRST LOVE (BY CLON)", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "A TRAP", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "DISCO BUS", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY" } },
                    { SongTitle = "RUN!", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "RUN TO YOU", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                    { SongTitle = "-REMIX- 2ND HIDDEN REMIX | REMIX 2-7 | NONSTOP REMIX 11", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
                    { SongTitle = "-REMIX- BANYA HIP-HOP REMIX | REMIX 3-3 | NONSTOP REMIX 13", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "-REMIX- BANYA HARD REMIX | REMIX 3-7 | NONSTOP REMIX 18 | C44", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
                    { SongTitle = "-REMIX- 3RD O.B.G DIVA REMIX | REMIX 3-1", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "-REMIX- PARK MEE KYUNG REMIX | REMIX 3-2", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "-REMIX- PARK JIN YOUNG REMIX | REMIX 3-4", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "-REMIX- NOVASONIC REMIX | REMIX 3-5 | NONSTOP REMIX 09", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
                    { SongTitle = "-REMIX- SECHSKIES REMIX | REMIX 4-1", Charts = { "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
                },
            },
            {   SortName = "Normal",
                AvailableSongs = {
                    { SongTitle = "MR. LARPUS", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "OH! ROSA", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "FIRST LOVE (BY BANYA)", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "SOLITARY", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "BETRAYER", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "RUN TO YOU", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "SUMMER OF LOVE", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "MAN & WOMAN", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "KISS", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "SAD SALSA", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "A TRAP", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "DISCO BUS", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "FIRST LOVE (BY CLON)", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "RUN!", Charts = { "OBGSE-NORMAL" } },
                    { SongTitle = "WITH MY LOVER", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "CLOSE YOUR EYES", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "NIGHTMARE", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "FREE STYLE", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "DON'T BOTHER ME | CAUTION", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "LOVE SONG", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "LOVER'S GRIEF | SORROW", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "TO THE TOP", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "PUYO PUYO", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "TIME TO SAY GOODBYE", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "OK? OK! (BEAUTY AND THE BEAST)", Charts = { "3RD-NORMAL" } },
                    { SongTitle = "ANOTHER TRUTH | CORDIALITY", Charts = { "3RD-NORMAL" } },
                },
            },
            {   SortName = "Hard",

            },
            {   SortName = "Crazy",

            },
            {   SortName = "Double",

            },
            {   SortName = "Single Progressive",

            },
            {   SortName = "Double Progressive",

            },
        },
    },
    {	MixName = "Perfect Collection",
        SortingMethods = {
            {   SortName = "Full Display Mode",

            },
            {   SortName = "Normal",

            },
            {   SortName = "Hard",

            },
            {   SortName = "Crazy",

            },
            {   SortName = "Double",

            },
            {   SortName = "Single Progressive",

            },
            {   SortName = "Double Progressive",

            },
        },
    },
    {	MixName = "Extra",
        SortingMethods = {
            {   SortName = "Full Display Mode",

            },
            {   SortName = "Normal",

            },
            {   SortName = "Hard",

            },
            {   SortName = "eXtra eXpert",

            },
            {   SortName = "Double",

            },
            {   SortName = "eXtra eXpert Double",

            },
            {   SortName = "Single Progressive",

            },
            {   SortName = "Double Progressive",

            },
        },
    },
}

return MixDatabase